### ISSUE TITLE
python.app and matplotlib(given version) cannot be found

### ISSUE THREAD

**Issue by romanchyla** [ericmjl/Network-Analysis-Made-Simple#1]
hi, i tried to follow instructions from readme - and the conda env create was failing with "cannot find package"

so i removed the matplotlib version number
and then finally python.app package 

then i could create the environemtn, but was getting 'unknown symbol' during 'import hiveplot'

after bit of head scratching, found the solution

```
sudo apt-get install libqt4-dev
conda install sip
conda install pyqt
```

I think it might be a good idea to test the instructions in a fresh docker container, environments have probably changed (are changing)

**Comment by ericmjl** [comment]
Thanks, @romanchyla for giving this a shot. I have updated the `environment.yml` specifications without version numbers. This works under a Linux environment that I have access to. Do you have any knowledge on how to get access to free Windows and Linux docker containers?
