### ISSUE TITLE
Getting Started - How to run Python Notebook?

### ISSUE THREAD

**Issue by RyPeck** [ericmjl/Network-Analysis-Made-Simple#10]
Hey Eric - I got tripped up first few minutes of the class because I didn't realize how to run a notebook - would be good as part of the class setup or first few slides to have a test and instruction for running the notebook and make sure everything is OK.

**Comment by ericmjl** [comment]
Thanks, @RyPeck! I resolved it in commit [af6d433](https://github.com/ericmjl/Network-Analysis-Made-Simple/commit/af6d433ddaeb905ac4ec7a3387ecd55c31b862af)
