### ISSUE TITLE
node_color issue for CircosPlot

### ISSUE THREAD

**Issue by hegrich** [ericmjl/Network-Analysis-Made-Simple#107]
I receive an issue when trying to color nodes by a node attribute.  Each node has an attribute labeled 'attr_1' and each attribute value is a string. The CircosPlot object returns a KeyError: 'attr_1'

**Comment by ericmjl** [comment]
Thanks for raising this, @hegrich - did you resolve it, therefore you closed the issue? Please let me know.

**Comment by hegrich** [comment]
Yes it is resolved @ericmjl - while you are here, is there a way to add a legend for each node/edge color? I used the group_label_position parameter from the inherited BasePlot but it didn't do anything.

**Comment by hegrich** [comment]
Hi @ericmjl - yes it is resolved. Thank you for the timely response. This package very helpful!
