### ISSUE TITLE
"nxviz ":  ModuleNotFoundError: No module named 'nxviz'

### ISSUE THREAD

**Issue by vinuthnaL** [ericmjl/Network-Analysis-Made-Simple#118]
Hi, 
   i want to work with Circos Plots and when i gave " from nxviz.plots import CircosPlot"  I am getting this error  **ModuleNotFoundError: No module named 'nxviz'** .
 To add it I gave  "! conda install -c conda-forge nxviz" which is giving me error 

**Collecting package metadata (current_repodata.json): ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000000662A280048>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)'))"))**

NOTE : I am working with spyder in Anaconda. ..all the commands are given in IPython Console.

Can someone please help me out with this issue ..??

Thanks in Advance..!

**Comment by ericmjl** [comment]
According to the error trace:

> HTTP errors are often intermittent, and a simple retry will get you on your way.

Try it again, and if it doesn’t work, the only suggestion I can think of is to contact your network administrator (as I definitely won’t have knowledge of the network that you’re using).
