### ISSUE TITLE
ebook-style

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/Network-Analysis-Made-Simple#135]
I'd like to upgrade the repository a bit here, and make it into a format that is simultaneously compatible with:

- Running a tutorial
- Publishing an online book
- Exporting as a collection of PDFs to be printed.

This will be done in a branch. I'll be running some experiments on my personal static site server to see how this can be done most effectively.

**Comment by ericmjl** [comment]
@MridulS check this out! http://nams.ericmjl.com/

Still in the early stages, but the rewrite is ongoing.

**Comment by MridulS** [comment]
This is great!

Let me know if I should make changes to NB7 and 8 to make this work with the book (I probably need to add more explanations too!)

**Comment by ericmjl** [comment]
Yes, let's definitely get that in.

There's a pattern I've started using in there.

We can dispense with instructor/student dichotomy if we:

- Put solutions in the `nams.solutions` subpackage as functions which we then import back.
- This allows us to use code that looks like:

```python
from nams.solutions.ch1 import adding_students

#### REPLACE THE NEXT LINE WITH YOUR ANSWER
G = adding_students(G)
```

Doing so thus allows us to:

1. Execute the notebook in its entirety during build time.
1. Keep the answers obscured from students.
1. Reveal answers right at the bottom of each notebook (like a book).

This gives us the versatility to use the notebooks both as a book and as a tutorial thing. The final thing I have to figure out is how to get the Docker build to be compatible with both running a Dokku web server _and_ a Jupyter server on Binder. Once that is done, we'll have a triple-use eBook/tutorial notebook. It'll be amazing!

**Comment by ericmjl** [comment]
@MridulS I think we're almost ready to merge in the latest changes! If I'm looking correctly, I think the Airport Network chapter is the last one left. No pressure, though. If you feel like you need more time, I'm OK with hiding it from the navigation until you PR it in. What do you think?

**Comment by MridulS** [comment]
I can get the last chapter in by next weekend. If you want to make a release before that feel free to do it :)


On 05-Jul-2020, at 01:30, Eric Ma <notifications@github.com<mailto:notifications@github.com>> wrote:



@MridulS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMridulS&data=02%7C01%7C%7C1d4101fae3c04a57bac808d82054ee7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637294896432590938&sdata=6asVS0AoAahgoD1vpKqxkPZqlwLVlymd%2B40w%2Fv5rOCw%3D&reserved=0> I think we're almost ready to merge in the latest changes! If I'm looking correctly, I think the Airport Network chapter is the last one left. No pressure, though. If you feel like you need more time, I'm OK with hiding it from the navigation until you PR it in. What do you think?

Stay safe out there!

**Comment by ericmjl** [comment]
Okie dokes, sounds good to me.

Btw, do you have a LeanPub account? Let’s publish Network Analysis Made Simple together as a proper e-Book up there.

**Comment by MridulS** [comment]
Looks good! Just created an account there. https://leanpub.com/u/MridulS


On 05-Jul-2020, at 04:18, Eric Ma <notifications@github.com<mailto:notifications@github.com>> wrote:

LeanPub

**Comment by ericmjl** [comment]
Closing this out, since we've crossed the book over the line! Thanks for all the effort in making the case studies, @MridulS!
