### ISSUE TITLE
Linux Anaconda 4.1.0 64bit circos install

### ISSUE THREAD

**Issue by NeonGoby** [ericmjl/Network-Analysis-Made-Simple#16]
Hi, I followed the instructions, install circos with pip install, checkenv.py failed with:

Traceback (most recent call last):
  File "checkenv.py", line 19, in <module>
    '{0} not present. Please install via pip or conda.'.format(p)
AssertionError: circos not present. Please install via pip or conda.

Re-ran pip install circos and got:

Requirement already satisfied (use --upgrade to upgrade): circos in /home/jh/anaconda3/envs/network/lib/python3.5/site-packages

**Comment by ericmjl** [comment]
Hi @NeonGoby, thanks for posting! There's an alternate way of checking whether you have Circos installed properly - in a Python REPL, can you `import circos`? If you get an IPython.kernel error, just ignore it; I'm just trying to make sure you don't encounter the `ImportError: No module named 'circos'
`.

As an alternate way of checking, can you try running all of Notebook 2 (Instructor version)? If you have no errors in there, you're also good to go.

If you have errors, please post them, and let me know!

**Comment by NeonGoby** [comment]
Hi Eric,

pip install put the following files in to the site-packages folder:

~/anaconda3/lib/python3.5/site-packages/Circos-1.1.dist-info $ lltotal 48

drwxr-xr-x   2 jh jh  4096 Jul  2 22:30 ./
drwxr-xr-x 202 jh jh 16384 Jul  2 22:30 ../
-rw-r--r--   1 jh jh    77 Jul  2 22:30 DESCRIPTION.rst
-rw-r--r--   1 jh jh     4 Jul  2 22:30 INSTALLER
-rw-r--r--   1 jh jh   435 Jul  2 22:30 METADATA
-rw-r--r--   1 jh jh   568 Jul  2 22:30 metadata.json
-rw-r--r--   1 jh jh   630 Jul  2 22:30 RECORD
-rw-r--r--   1 jh jh     1 Jul  2 22:30 top_level.txt
-rw-r--r--   1 jh jh    92 Jul  2 22:30 WHEEL

These looks too small to be a full package.

I did an anaconda search -t circosand it found a bioconda/circos package 
that I installed via:

conda install --channel https://conda.anaconda.org/bioconda circos

That install some perl script as well as a circos executable.

Even then I still cannot import circos

**Comment by ericmjl** [comment]
FWIW, I just uploaded Circos 1.2 to PyPI, which fixes the installation issue. I should really setup continuous integration on Circos, to ensure that `pip`-based installation works.

**Comment by NeonGoby** [comment]
Thanks the install from your github did the trick, the notebook 2 
instructor ran successfully.

Thank you very much, looking forward to next week.
