### ISSUE TITLE
'custom' can't be imported

### ISSUE THREAD

**Issue by ElArkk** [ericmjl/Network-Analysis-Made-Simple#161]
Hi!

First, thank you for making this cool resource openly available. I cloned the repo, set up the `nams` conda env and ran `setup.py`. However, in the second notebook lesson (`2-networkx-basics-student.ipynb`), it fails to import `custom` in the top cell. Same thing when trying on binder. Am I missing a setup step still?

**Comment by ericmjl** [comment]
Oh crap! I forgot  to archive the old notebooks. :smile:

Thanks for the catch. You're not missing anything - the notebooks are actually inside the `docs/` directory, and the custom `nams` package is automatically installed from github when you set up the conda env.

**Comment by ElArkk** [comment]
aah I should've looked more closely! Working now, thanks :)
