### ISSUE TITLE
No Python Version that Works

### ISSUE THREAD

**Issue by brian8128** [ericmjl/Network-Analysis-Made-Simple#17]
Hi, I'm trying to install the packages required for this tutorial and I'm running into a problem. Cirocos only likes Python 3.5 and refuses to conda install if I'm using Python 3.4

> scipy-2016-tutorial brian$ conda install -c ericmjl circos
> ...
> The following specifications were found to be in conflict:
> - circos
> - python 3.4*

But hiveplot only likes Python 3.4 and won't install in my Python 3.5 environment

> scipy-2016-tutorial brian$ conda install -c ericmjl hiveplot
> ...
> The following specifications were found to be in conflict:
> - hiveplot
> - python 3.5*

Any suggestions?

**Comment by ericmjl** [comment]
Thanks for the catch! I'm on my phone right now, but when I'm back I'll update both to accept any py3k!

**Comment by ericmjl** [comment]
@datamath28: can you specify your operating system version please? Just want to make sure I have the correct OS builds up on conda.

**Comment by datamath28** [comment]
El Capitan 10.11.3

**Comment by ericmjl** [comment]
Okay, can you try giving it a shot with conda? Alternatively, you can use `pip` to install `hiveplot` and `circos`. Their latest version numbers, by my admittedly bad versioning system, should be 0.1.8.2 and 1.3 respectively.
