### ISSUE TITLE
JupyterCon 2020 Binder Presentation is missing the data

### ISSUE THREAD

**Issue by fm75** [ericmjl/Network-Analysis-Made-Simple#180]
Attempting to run `notebooks/02-networkx-intro.ipynb` fails to load the class data, apparently trying to load it from a local directory.

Needs a datasets folder.

**Comment by ericmjl** [comment]
Thanks @fm75! I will push one change immediately to the repo so that it shows up.

**Comment by ericmjl** [comment]
@fm75 I pushed up commit `cbb12ae`, give the CI a moment or two to to rebuild, and it'll push directly to the JupyterCon2020 repo, which will also rebuild upon changes being pushed. Thanks again for the catch! :smile: Hope the tutorial brings value to you; please feel free to chime in here if you've got questions, or we can chat at Office Hours :).

**Comment by ericmjl** [comment]
Closing this issue as JupyterCon is over. Hope everyone had a great time with the tutorial :smile:.
