### ISSUE TITLE
sociopatterns dataset - out.sociopatterns-infectious

### ISSUE THREAD

**Issue by Hubercorp** [ericmjl/Network-Analysis-Made-Simple#194]
Hello there !
I was wondering why the dataset you are using from sociopatterns is structured that way: 
![image](https://user-images.githubusercontent.com/32447373/102535659-cc3a7a80-40a8-11eb-8261-f812080117f4.png)

while the one I see from their [website](http://www.sociopatterns.org/datasets/infectious-sociopatterns-dynamic-contact-networks/) is structured in a different way:
![image](https://user-images.githubusercontent.com/32447373/102536264-ab265980-40a9-11eb-8339-dc6d81981d96.png)

the source of your dataset is not working anymore:
https://west.uni-koblenz.de/konect/networks/sociopatterns-infectious

Thanks for the hardwork! I appriciate your book :)

Best regards, 

Jérôme

**Comment by ericmjl** [comment]
Hi @Hubercorp! Thanks for chiming in. I downloaded the original files many years ago (2014, if I remember correctly). Looks like indeed, the original Konect website is down. I also can't seem to access [konect.cc](http://konect.cc); are you able to?

I'm glad you're enjoying the material! It's always nice to hear from readers/learners.

**Comment by MridulS** [comment]
@ericmjl konect.cc is not "open-data" anymore, we should probably link to the sociopatterns website.

**Comment by ericmjl** [comment]
Good point, thanks @MridulS!
