### ISSUE TITLE
 from custom import load_data as cf

### ISSUE THREAD

**Issue by SalYah** [ericmjl/Network-Analysis-Made-Simple#198]
Hi; 
I am trying to find this custom package an I could not find it, is they any way to get it?

**Comment by ericmjl** [comment]
Hi @SalYah! I think that belongs to an outdated version of the notebooks. If you go to [the official website](https://ericmjl.github.io/Network-Analysis-Made-Simple/index.html) and click on the Binder link, you'll see we now import from a custom package called `nams`, which resides in the project root directory. Can I ask, where did you see this line? Do you have a link to a file in the repository?

**Comment by SalYah** [comment]
Thanks for your promote response and also thanks for the valuable material that you have presented. This link is down here: 
https://github.com/ericmjl/Network-Analysis-Made-Simple/blob/master/archive/2-networkx-basics-instructor.ipynb

Regards
SalYah

**Comment by ericmjl** [comment]
Got it! We don't use the archived notebooks anymore. I left them there just as a backup (in case I need to fish out material from there) for the latest notebooks, which are in the `notebooks/` directory instead. 

I'm going to close the issue, but please feel free to continue commenting if you have other questions!
