### ISSUE TITLE
hiveplot incompatible with python 3.4, 3.5?

### ISSUE THREAD

**Issue by jamesbev** [ericmjl/Network-Analysis-Made-Simple#2]
I get error messages from anaconda when attempting to install hiveplot in environments with alternatively python 3.4 and 3.5. Clean install with python 2.7, however. Requirement of python 3 perhaps incorrect?

**Comment by ericmjl** [comment]
Hi @jamesbev, thank you for this catch! Let me update the hiveplot requirements so that it works. :smile:

**Comment by ericmjl** [comment]
@jamesbev, if I may ask, how are you installing the hiveplot package? Is it via pip or conda?

**Comment by jamesbev** [comment]
Hi Eric, I initially attempted to conda install hiveplot in an environment
I created. This generated the apparent conflict between hiveplot and python
3.*. I then followed your instructions explicitly and the pip install
worked without issue! So thanks for the yaml.

Might make sense to explicitly call out the need to pip install hiveplot.



On Thursday, November 19, 2015, Eric Ma <notifications@github.com> wrote:

> @jamesbev <https://github.com/jamesbev>, if I may ask, how are you
> installing the hiveplot package? Is it via pip or conda?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericmjl/Network-Analysis-Made-Simple/issues/2#issuecomment-158279672>
> .
>


-- 
James

Sent from my iPhone

**Comment by ericmjl** [comment]
@jamesbev Ah yes! Thank you, I will update the instructions there. By the way, credit to another fellow githubber for the YAML file, I dare not take credit for that. :smile:

**Comment by jamesbev** [comment]
Excellent! One more suggestion--you may want to throw jupyter in the yaml
as well. When I activated the 'network' environment and went to open the
first notebook, I realized jupyter remained to be installed.

Thanks again!

On Friday, November 20, 2015, Eric Ma <notifications@github.com> wrote:

> @jamesbev <https://github.com/jamesbev> Ah yes! Thank you, I will update
> the instructions there. By the way, credit to another fellow githubber for
> the YAML file, I dare not take credit for that. [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericmjl/Network-Analysis-Made-Simple/issues/2#issuecomment-158280931>
> .
>


-- 
James

Sent from my iPhone

**Comment by ericmjl** [comment]
Great catch, @jamesbev! Many thanks for catching and posting these issues!

**Comment by ericmjl** [comment]
@jamesbev, I'm going to close this issue, but feel free to re-open it if you find more bugs! Thanks again!
