### ISSUE TITLE
Use Lab interface by default for mybinder links?

### ISSUE THREAD

**Issue by MridulS** [ericmjl/Network-Analysis-Made-Simple#216]
It's better (IMO) to have links to the lab interface on mybinder
instead of the classic notebooks. It's easier to move around
different notebooks without going back to the nams website to look
for the direct link.

Once this is merged https://github.com/greenape/mknotebooks/pull/329
we should be able to use lab.

@ericmjl What do you think?

**Comment by ericmjl** [comment]
We should do it, @MridulS! Thanks for handling the PR :100:. This means we only need to change the config a bit, right?

**Comment by MridulS** [comment]
yeah, assuming there is a release of or need to pin to the master branch to use it.
