### ISSUE TITLE
Bug in notebook 3 for breadth first search

### ISSUE THREAD

**Issue by ghirlekar** [ericmjl/Network-Analysis-Made-Simple#3]
Queue size is exponentially growing and unbounded since same nodes are added in queue multiple times without checking if they have been traversed before. I think the algorithm also gets trapped in cycles, but I have not tested that.

I solved the issue by adding a list of visited nodes and maintaining a unexplored queue with unique elements and exclusive from visited nodes. Here's my code.

```
def path_exists(node1, node2, G, debug=False):
    """
    This function checks whether a path exists between two nodes (node1, node2) in graph G.
    """
    # Fill in code below
    queue = G.neighbors(node1)
    visited_nodes = []
    destination = node2
    
    for node in queue:
        visited_nodes.append(node)
        if(debug): print(visited_nodes, '\t', queue)
        neighbors = G.neighbors(node)
        queue.remove(node)
        [queue.append(neighbor) for neighbor in neighbors if neighbor not in visited_nodes and neighbor not in queue]
        if node2 in neighbors:
            print('Path exists between nodes {0} and {1}'.format(node1, node2))
            return True
        
    print('Path does not exist between nodes {0} and {1}'.format(node1, node2))
    return False
```

I also made a small graph as a test environment with a single cycle and a single isolated node.
```
G1 = nx.Graph()
G1.add_nodes_from([1,2,3,4])
G1.add_edges_from([(1,2),(2,3),(1,3)])
nx.draw(G1)
```

And a couple test cases 
```
path_exists(2,4, G1, debug=True)
path_exists(1,3, G1, debug=True)
```

Gets me the output
```
[1] 	 [1, 3]
[1, 2] 	 [3, 2]
Path does not exist between nodes 2 and 4

[2] 	 [2, 3]
Path exists between nodes 1 and 3
```

By looking over the debug output, I think it solves the issue by conclusively saying there is no path once it has traversed each node in the graph.

Let me know if you find this helpful.

**Comment by ericmjl** [comment]
This is great, thank you so much @ghirlekar! I will update the notebooks with your code, and reference it in the code & acknowledgments.
