### ISSUE TITLE
Trying to Clone Repository

### ISSUE THREAD

**Issue by adownard** [ericmjl/Network-Analysis-Made-Simple#36]
I tried cloning the git repository into anaconda on the terminal line but the first few times I tried it, it took forever to load and terminated before it finished due to an error. The error was "fatal: early EOFs: 82% (850/1036), 66.21 MiB | 28.00 Kib/s \n fatal: The remote end hung up unexpectedly \n fatal: index-pack failed \n error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054"

**Comment by ericmjl** [comment]
@adownard thanks for posting. That's the first time I've seen this, though my first thoughts are that it's an internet connectivity issue, perhaps? If you can't get it downloaded by the first day, no worries - I will have backup copies on USB flash drives available for everybody.
