### ISSUE TITLE
the US airport network dataset

### ISSUE THREAD

**Issue by wanghz18** [ericmjl/Network-Analysis-Made-Simple#369]
Hello there!
I am interested in the passenger dataset(the US airport network dataset) and want to work on it further. Could you provide the formal link to the dataset for citing it in the paper? Thank you for your effort in this repository!

**Comment by MridulS** [comment]
@wanghz18 https://www.transtats.bts.gov/Fields.asp?gnoyr_VQ=FIL should have the details to reconstruct the dataset in the notebook. You can extract data from https://www.transtats.bts.gov/DL_SelectFields.aspx?gnoyr_VQ=FIL&QO_fu146_anzr=Nv4%20Pn44vr45 too.

**Comment by wanghz18** [comment]
Thank you very much!
