### ISSUE TITLE
On the Degree Centrality vs Number of neighbors scatter plot

### ISSUE THREAD

**Issue by muthazhagu** [ericmjl/Network-Analysis-Made-Simple#4]
The scatter plot for degree centrality vs number of neighbors gives a nice straight line with a positive slope when using the following code (same as the one from the instructor notes) - 

`neighbors = [len(G.neighbors(node)) for node in G.nodes()]`

When using the code below, it gives a very wonky graph.
`number_of_neighbors = [len(item[1]) for item in sorted(node_and_connections, key=lambda x: len(x[1]), reverse=True)]`

May want to emphasize this point in the presentation.

**Comment by ericmjl** [comment]
Thanks for the reminder, @muthazhagu! I will keep that in mind. I think guaranteeing that the order that the nodes are added in matters, as it is true that dictionaries are not intrinsically ordered to begin with.
