### ISSUE TITLE
nxviz requirements and checkenv.py problems

### ISSUE THREAD

**Issue by buhl** [ericmjl/Network-Analysis-Made-Simple#45]
Using `pew` to create my virtual environment.

I had to install nxviz first to avoid these warnings
```
nxviz 0.3.6 has requirement matplotlib==2.1.2, but you'll have matplotlib 2.2.2 which is incompatible.
nxviz 0.3.6 has requirement networkx==2.0, but you'll have networkx 2.1 which is incompatible.
nxviz 0.3.6 has requirement numpy==1.14.0, but you'll have numpy 1.14.3 which is incompatible.
```
I did this by doing the following

```
$ pew new network
(network) $ pip install nxviz
(network) $ pip install -r requirements.txt
```
I don't know if this is an accepted solution, the notebooks seems to work, though.

I also had a little issue with the checkenv.py file. I had to change python-louvain to community to get it to pass my environment.

```patch
diff --git a/checkenv.py b/checkenv.py
index 24d7f30..b2757c4 100644
--- a/checkenv.py
+++ b/checkenv.py
@@ -10,7 +10,7 @@ def check_import(packagename):
         return False

 packages = ['networkx', 'numpy', 'matplotlib', 'hiveplot', 'pandas',
-            'jupyter', 'nxviz', 'python-louvain']
+            'jupyter', 'nxviz', 'community']

 all_passed = True
```

If I did something that will bite me in training I'd appreciate a heads up.

```patch
--- nxviz_fifth 2018-05-05 12:19:21.203861367 +0200
+++ nxviz_first 2018-05-05 12:17:57.912863465 +0200
@@ -23,15 +23,14 @@
 jupyter-client==5.2.3
 jupyter-console==5.2.0
 jupyter-core==4.4.0
-kiwisolver==1.0.1
 MarkupSafe==1.0
-matplotlib==2.2.2
+matplotlib==2.1.2
 mistune==0.8.3
 nbconvert==5.3.1
 nbformat==4.4.0
-networkx==2.1
+networkx==2.0
 notebook==5.4.1
-numpy==1.14.3
+numpy==1.14.0
 nxviz==0.3.6
 palettable==3.1.0
 pandas==0.22.0
```
As you can see the three packages mentioned above in the warnings are no longer the current version and I also seem to be missing kiwisolver for some reason when installing nxviz first.

**Comment by ericmjl** [comment]
@buhl thank you for posting this issue!

I'm going to make sure python-louvain is made into a conda-forge package, so that it doesn't have to be installed.

As for those errors, they don't appear to affect the notebooks, so I think you'll be fine. Nonetheless, I'll be working right up to the tutorial starts to make sure the same errors don't show up for other participants.

**Comment by buhl** [comment]
It works now.
```shell
$ python checkenv.py
All checks passed. Your environment is good to go
$ 
```

nxviz is still complaining about incompatible versions
```
nxviz 0.3.6 has requirement matplotlib==2.1.2, but you'll have matplotlib 2.2.2 which is incompatible.
nxviz 0.3.6 has requirement networkx==2.0, but you'll have networkx 2.1 which is incompatible.
nxviz 0.3.6 has requirement numpy==1.14.0, but you'll have numpy 1.14.3 which is incompatible.
```
This could be be fixed by hardcoding the package versions in requirements.txt if it causes problems.
I just went through all the ipynb files and they seem to work fine with one exception in bonus-3-matrices.ipynb where the HTML function in the last cells has not been imported/defined. But I guess you are still working on that document.

Looking forward to the training :)

**Comment by ericmjl** [comment]
> nxviz is still complaining about incompatible versions

I'll cut a new nxviz release soon, which will update the requirements.

> But I guess you are still working on that document.

You're absolutely right about that!

**Comment by ericmjl** [comment]
Will keep this issue open until after the PyCon tutorial is over.
