### ISSUE TITLE
python-louvain issues

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/Network-Analysis-Made-Simple#46]
@MridulS can you please build a conda-forge package for python-louvain? Its presence as a pip-installed package is causing some issues.

**Comment by ericmjl** [comment]
I've started the PR: https://github.com/conda-forge/staged-recipes/pull/5797

**Comment by ericmjl** [comment]
Btw, I just checked: python-louvain requires networkx < 2.0.0. This tutorial is about teaching networkx >= 2.0.0. This is going to be an issue. Is Louvain absolutely required, or can you use a different community detection method?

**Comment by MridulS** [comment]
They updated it last year.
Does it show up while conda install?

python-louvain>=0.9 works with networkx>=2.0

I'm using with networkx==2.1 and python-louvain=0.10

**Comment by ericmjl** [comment]
Interesting: what about the GitHub repo then? https://github.com/taynaud/python-louvain/blob/master/requirements.txt

**Comment by ericmjl** [comment]
I guess everything should be fine, now that the python-louvain package is up on conda-forge. Closing this issue.
