### ISSUE TITLE
Trouble with nxviz installation

### ISSUE THREAD

**Issue by horakmatt** [ericmjl/Network-Analysis-Made-Simple#73]
I am struggling to install the nxviz package with pip.  It gets as far as fulltoc and stops with the following message:

Collecting sphinxcontrib-fulltoc==1.2.0 (from nxviz)
Downloading https://files.pythonhosted.org/packages/8e/a6/d1297db9b75650681e5429e92e13df139ee6b64303ff1b2eea4ebd32c0a9/sphinxcontrib-fulltoc-1.2.0.tar.gz
Complete output from command python setup.py egg_info:
Download error on https://pypi.org/simple/pbr/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833) -- Some packages may not be found!
Couldn't find index page for 'pbr' (maybe misspelled?)
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833) -- Some packages may not be found!
No local packages or working download links found for pbr
Traceback (most recent call last):
...

I have a similar problem when I try install from a local archive downloaded from pipit.org.  Is there some solution I could try?

**Comment by ericmjl** [comment]
@horakmatt thanks for pinging in. I'm sorry to hear that you are facing this issue.

I'm not quite sure why you would have an SSL issue. Have you tried installing `sphinxcontrib-fulltoc` independently? To do so:

```python
$ pip install sphinxcontrib-fulltoc
```

(Version number not necessary as `1.2.0` is the latest version.)

**Comment by MridulS** [comment]
Closing this as this was probably a network/config issue.
