### ISSUE TITLE
Alternate implementation of Exercise in 3-hubs-and-paths-student

### ISSUE THREAD

**Issue by dgerlanc** [ericmjl/Network-Analysis-Made-Simple#75]
Exercise¶
Can you create a ranked list of the importance of each individual, based on the number of neighbors they have? (3 min.)

Hint: One suggested output would be a list of tuples, where the first element in each tuple is the node ID (an integer number), and the second element is the number of neighbors that it has.

Hint: Python's sorted(iterable, key=lambda x:...., reverse=True) function may be of help here.

In 2 lines with minimal materialization b/c uses a generator expression.

```
gen = ((len(list(G.neighbors(x))), x) for x in G.nodes())
sorted(gen, reverse=True)
```

**Comment by ericmjl** [comment]
@dgerlanc likewise also linked in the notebooks!
