### ISSUE TITLE
ffmpeg needed for nams environment

### ISSUE THREAD

**Issue by cbcunc** [ericmjl/Network-Analysis-Made-Simple#96]
In order for checkenv.py to pass, ffmpeg must be installed. It is not included in the environment dependencies.

**Comment by cbcunc** [comment]
Wrong repo. Sorry.

**Comment by cbcunc** [comment]
No, sorry again, this is the right repo.

**Comment by ericmjl** [comment]
@cbcunc thanks for pinging in. I will add that in as a dependency asap.

**Comment by ericmjl** [comment]
Just done!
